name: PR Tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: pyleo
        environment-file: environment.yml
        auto-activate-base: false

    - name: Install test dependencies
      run: |
        conda activate pyleo
        pip install pytest-xdist nbmake
        conda list

    - name: Check for failures
      run: |
        conda activate pyleo
        pytest --nbmake -v --tb=long --nbmake-timeout=3600 notebooks/*ipynb
