name: PR Tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pyleo
        environment-file: environment.yml
        auto-activate-base: false
    - name: Install test dependencies
      run: |
        conda activate pyleo
        pip install pytest-xdist nbmake
        conda list
    - name: Test notebooks
      run: |
        conda activate pyleo
        pytest --nbmake --forked -n=auto --nbmake-timeout=3600 notebooks/*ipynb
